[package]
name = "pgdatetime"
version = "0.1.0"
authors = ["Ivor Huang <ivorhuang_hjd@163.com>", "David Li <davidli2010@foxmail.com>"]
edition = "2018"

[[bench]]
name = "benchmark"
harness = false

[dev-dependencies]
criterion = "^0.3"
